name: Deploy to GCP VM
on:
  push:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Listing files
      run: ls -altr

    - name: Lising env variables
      run: env

    - name: ENV names
      run: echo "We are deploying in ${{ vars.ENV_NAME }}"
