name: CDO Workflow
on: push
jobs:
  CDO:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: OS Version details
      run: cat /etc/os-release > os-details.txt
    - uses: actions/upload-artifact@v4
      with:
        name: os-details-artifact
        path: .github/workflows/os-details.txt
    - name: Listing files
      run: ls -ltr
    - name: Is os-details.txt file exists
      run: |
        ls -lr | grep -i os-details
        cat os-details.txt
    
  read_file_from_CDO_job:
    needs: CDO
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: os-details-artifact
    - name: listing files
      run: ls -ltr
    - name: Is file exists
      run: ls -ltr | grep os-details.txt
    - name: Reading file content
      run: cat os-details.txt
        
  
