name: CDO Workflow
on: push
jobs:
  CDO:
    runs-on: ubuntu-latest
    steps:
    - name: OS Version details
      run: cat /etc/os-release
    - name: Listing files
      run: ls -ltr
    - name: Is README.md file exists
      run: ls -lr | grep -i readme.md
    
