name: CDO Workflow
on: push
jobs:
  CDO:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: OS Version details
      run: cat /etc/os-release > os-details.txt
    - name: Listing files
      run: ls -ltr
    - name: Is os-details.txt file exists
      run: |
        ls -lr | grep -i os-details
        cat os-details.txt
    
